# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:coverage
    - id: getJson
      run: |
        content=`cat coverage/coverage-summary.json`
        echo "::set-output name=coverageJson::$content"
  
  badge_job:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coverage badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: coverage
          LABEL: 'Coverage'
          ICON: 'github'
          STATUS: ${{ fromJSON(needs.build.steps.getJson.outputs.coverage).total.statements.pct }}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
